# This workflow will builds and runs tests
name: Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build and verify with default nexus version
        run: mvn -B verify --file pom.xml
      - name: Build and verify with nexus 3.30.0
        run: mvn -B -Dtest.target.nexus.version=3.30.0 verify --file pom.xml
